project_id = "jeqmnulrerilwixohvgw"

[functions.ai-restaurant-agent]
verify_jwt = false

[functions.copilot-chat]
verify_jwt = false

[functions.sustainability-ai-analysis]
verify_jwt = false

[functions.supplier-analyzer]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.business-opening-assistant]
verify_jwt = false

[functions.ai-proactive-alerts]
verify_jwt = false

[functions.feedback-ai-analysis]
verify_jwt = false

[functions.recipe-ai-assistant]
verify_jwt = false

[functions.sales-ai-projections]
verify_jwt = false

[functions.support-ai-assistant]
verify_jwt = false

[functions.social-ai-analysis]
verify_jwt = false

[functions.brand-ai-generator]
verify_jwt = false

[functions.loyalty-ai-engine]
verify_jwt = false

[functions.maturity-ai-engine]
verify_jwt = false
