project_id = "jeqmnulrerilwixohvgw"

[functions.ai-restaurant-agent]
verify_jwt = false

[functions.copilot-chat]
verify_jwt = false

[functions.sustainability-ai-analysis]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true
