// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile and restaurants",
  description: "Returns the signed-in RestroWizard user's basic profile info and the restaurants they own (id, name, city, cuisine).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: businesses, error } = await supabase.from("restaurant_businesses").select("id, name, business_type, cuisine_type, city, country, opening_date").eq("owner_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      restaurants: businesses ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-menu-items.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_menu_items_default = defineTool2({
  name: "list_menu_items",
  title: "List menu items",
  description: "List the signed-in user's menu items (name, category, price, cost). Optionally filter by a text query on name.",
  inputSchema: {
    query: z.string().trim().optional().describe("Optional text to filter items by name (ILIKE)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max items to return. Default 50.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("menu_items").select("id, name, category, price, cost, is_available").eq("user_id", ctx.getUserId()).order("name").limit(limit ?? 50);
    if (query) q = q.ilike("name", `%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-inventory-items.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_inventory_items_default = defineTool3({
  name: "list_inventory_items",
  title: "List inventory items",
  description: "List the signed-in user's inventory items with current stock. Optional low_stock_only flag returns only items at or below par level.",
  inputSchema: {
    low_stock_only: z2.boolean().optional().describe("If true, only return items at or below par_level."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max items to return. Default 50.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ low_stock_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("inventory_items").select("*").eq("user_id", ctx.getUserId()).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let items = data ?? [];
    if (low_stock_only) {
      items = items.filter((it) => {
        const stock = Number(it.current_stock ?? it.stock ?? 0);
        const par = Number(it.par_level ?? it.min_stock ?? 0);
        return par > 0 && stock <= par;
      });
    }
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_orders_default = defineTool4({
  name: "list_recent_orders",
  title: "List recent orders",
  description: "Return the signed-in user's most recent restaurant orders (id, status, total, created_at).",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max orders to return. Default 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("restaurant_orders").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-reservations.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reservations_default = defineTool5({
  name: "list_reservations",
  title: "List reservations",
  description: "Return the signed-in user's table reservations. Set upcoming_only=true to return only reservations from today onward.",
  inputSchema: {
    upcoming_only: z4.boolean().optional().describe("If true, only return reservations with date >= today."),
    limit: z4.number().int().min(1).max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ upcoming_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    let q = supabase.from("table_reservations").select("*").eq("user_id", ctx.getUserId()).order("reservation_date", { ascending: true }).limit(limit ?? 50);
    if (upcoming_only) {
      const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      q = q.gte("reservation_date", today);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { reservations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-latest-diagnosis.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.21.0";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_diagnosis_default = defineTool6({
  name: "get_latest_diagnosis",
  title: "Get latest maturity diagnosis",
  description: "Return the most recent restaurant maturity diagnosis for the signed-in user, including scores and AI summary if present.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser6(ctx);
    const { data, error } = await supabase.from("maturity_diagnoses").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(1);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const diagnosis = data?.[0] ?? null;
    return {
      content: [
        { type: "text", text: diagnosis ? JSON.stringify(diagnosis, null, 2) : "No diagnosis found." }
      ],
      structuredContent: { diagnosis }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jeqmnulrerilwixohvgw";
var mcp_default = defineMcp({
  name: "restrowizard-mcp",
  title: "RestroWizard",
  version: "0.1.0",
  instructions: "Tools for a RestroWizard restaurant owner's own data: profile and restaurants, menu items, inventory, recent orders, reservations, and the latest maturity diagnosis. All tools act as the signed-in user; RLS scopes results to that user's restaurant.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_menu_items_default,
    list_inventory_items_default,
    list_recent_orders_default,
    list_reservations_default,
    get_latest_diagnosis_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
