-- Add new columns to restaurant_websites for enhanced features (BentoBox/Popmenu inspired)
ALTER TABLE public.restaurant_websites
ADD COLUMN IF NOT EXISTS og_image_url text,
ADD COLUMN IF NOT EXISTS og_title text,
ADD COLUMN IF NOT EXISTS og_description text,
ADD COLUMN IF NOT EXISTS schema_type text DEFAULT 'Restaurant',
ADD COLUMN IF NOT EXISTS featured_items jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS testimonials jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS promo_banner_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS promo_banner_text text,
ADD COLUMN IF NOT EXISTS promo_banner_link text,
ADD COLUMN IF NOT EXISTS promo_banner_bg_color text,
ADD COLUMN IF NOT EXISTS announcement_bar_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS announcement_bar_text text,
ADD COLUMN IF NOT EXISTS popup_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS popup_title text,
ADD COLUMN IF NOT EXISTS popup_content text,
ADD COLUMN IF NOT EXISTS popup_cta_text text,
ADD COLUMN IF NOT EXISTS popup_cta_link text,
ADD COLUMN IF NOT EXISTS popup_image_url text,
ADD COLUMN IF NOT EXISTS newsletter_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS instagram_feed_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS instagram_handle text,
ADD COLUMN IF NOT EXISTS google_maps_embed_url text,
ADD COLUMN IF NOT EXISTS whatsapp_number text,
ADD COLUMN IF NOT EXISTS whatsapp_message text,
ADD COLUMN IF NOT EXISTS ordering_platforms jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS reservation_platforms jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS custom_sections jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS footer_text text,
ADD COLUMN IF NOT EXISTS show_powered_by boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS layout_variant text DEFAULT 'classic',
ADD COLUMN IF NOT EXISTS hero_style text DEFAULT 'fullscreen',
ADD COLUMN IF NOT EXISTS hero_video_url text,
ADD COLUMN IF NOT EXISTS color_scheme text DEFAULT 'auto',
ADD COLUMN IF NOT EXISTS facebook_pixel_id text,
ADD COLUMN IF NOT EXISTS gtm_id text,
ADD COLUMN IF NOT EXISTS tiktok_pixel_id text;